<template>
  <div>
    <h1 class="text-3xl font-bold text-gray-900 mb-8">Dashboard</h1>

    <!-- Stats Cards -->
    <div class="grid grid-cols-7 gap-4 mb-8" v-if="store.stats">
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-marketing">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Leads</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Total leads submitted across all sources. Includes new, qualified, and converted.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.leads.total }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-sales">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Open Deals</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Deals actively in the pipeline: contacted, in conversation, or offer sent. Excludes closed.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.deals.open }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-legal">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Tasks</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Agent task queue: pending, processing, completed, and failed tasks across all agents.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.tasks.total }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-accounting">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Invoices</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Invoices generated by the Accounting agent after deals are won and legal validation passes.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.invoices.total }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-email">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Emails Sent</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Outbound emails successfully delivered: cold outreach, proposals, follow-ups, invoices, and satisfaction checks.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.emails.sent }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-purple-500">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Research</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Completed market research reports generated by the Marketing agent (trends, competitors, opportunities).
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.research?.completed || 0 }}</p>
      </div>
      <div class="bg-white rounded-lg shadow p-4 border-l-4 border-pink-500">
        <div class="flex items-center justify-between mb-1">
          <p class="text-sm text-gray-500">Content</p>
          <span class="relative group text-gray-300 text-xs cursor-default select-none">ⓘ
            <span class="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-44 bg-gray-800 text-white text-xs rounded px-2 py-1.5 hidden group-hover:block z-10 text-center shadow-lg pointer-events-none">
              Social media content drafts (Instagram & LinkedIn) created by the Marketing agent from research insights.
            </span>
          </span>
        </div>
        <p class="text-2xl font-bold">{{ store.stats.content?.drafts || 0 }}</p>
      </div>
    </div>

    <!-- Pending Offer Approvals -->
    <PendingOffers ref="pendingOffersRef" />

    <!-- Sales Pipeline -->
    <div class="mb-8 bg-white rounded-lg shadow" v-if="store.stats">
      <div class="p-4 border-b">
        <h2 class="text-lg font-semibold">Sales Pipeline</h2>
      </div>
      <div class="p-4">
        <!-- Pipeline stages -->
        <div class="flex items-stretch gap-2 mb-6">
          <div
            v-for="stage in pipelineStages"
            :key="stage.key"
            class="flex-1 rounded-lg p-3 text-center"
            :class="stage.bg"
          >
            <p class="text-xs font-medium mb-1" :class="stage.label">{{ stage.name }}</p>
            <p class="text-2xl font-bold" :class="stage.text">{{ store.stats.deals[stage.key] ?? 0 }}</p>
            <p class="text-xs mt-1" :class="stage.label">deals</p>
          </div>
          <div class="flex items-center text-gray-300 text-xl font-thin select-none">›</div>
          <div class="flex-1 rounded-lg p-3 text-center bg-green-50">
            <p class="text-xs font-medium mb-1 text-green-600">Closed Won</p>
            <p class="text-2xl font-bold text-green-700">{{ store.stats.deals.closed_won ?? 0 }}</p>
            <p class="text-xs mt-1 text-green-600">deals</p>
          </div>
          <div class="flex-1 rounded-lg p-3 text-center bg-red-50">
            <p class="text-xs font-medium mb-1 text-red-500">Closed Lost</p>
            <p class="text-2xl font-bold text-red-600">{{ store.stats.deals.closed_lost ?? 0 }}</p>
            <p class="text-xs mt-1 text-red-500">deals</p>
          </div>
        </div>

        <!-- Summary metrics -->
        <div class="grid grid-cols-3 gap-4 border-t pt-4">
          <div>
            <p class="text-xs text-gray-500 mb-1">Pipeline Value</p>
            <p class="text-xl font-bold text-gray-900">{{ formatCurrency(store.stats.deals.pipelineValue) }}</p>
          </div>
          <div>
            <p class="text-xs text-gray-500 mb-1">Won Revenue</p>
            <p class="text-xl font-bold text-green-700">{{ formatCurrency(store.stats.deals.wonValue) }}</p>
          </div>
          <div>
            <p class="text-xs text-gray-500 mb-1">Win Rate</p>
            <p class="text-xl font-bold text-gray-900">
              {{ store.stats.deals.winRate != null ? store.stats.deals.winRate + '%' : '—' }}
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-8">
      <!-- Agent Pipeline (left) -->
      <div>
        <AgentPipeline />
      </div>

      <!-- Live Events Feed (right) -->
      <div class="bg-white rounded-lg shadow">
        <div class="p-4 border-b flex justify-between items-center">
          <h2 class="text-lg font-semibold">Live Agent Events</h2>
          <span
            :class="store.isWorkflowRunning ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-600'"
            class="px-3 py-1 rounded-full text-xs font-medium"
          >
            {{ store.isWorkflowRunning ? 'Workflow Running' : 'Idle' }}
          </span>
        </div>
        <div class="p-4 max-h-[500px] overflow-y-auto space-y-3">
          <div
            v-for="(event, i) in store.agentEvents"
            :key="i"
            class="p-3 rounded-lg border text-sm"
            :class="getEventClass(event)"
          >
            <div class="flex justify-between items-start">
              <span class="font-medium">{{ getAgentLabel(event.agent) }}</span>
              <span class="text-xs text-gray-400">{{ formatTime(event.timestamp) }}</span>
            </div>
            <p class="mt-1">{{ event.message }}</p>
            <div v-if="event.reasoning" class="mt-2 space-y-1">
              <p
                v-for="(step, j) in event.reasoning"
                :key="j"
                class="text-xs text-gray-600 pl-2 border-l-2 border-gray-200"
              >
                {{ step }}
              </p>
            </div>
          </div>
          <p v-if="store.agentEvents.length === 0" class="text-gray-400 text-center py-8">
            No events yet. Submit a lead to start the workflow.
          </p>
        </div>
      </div>
    </div>

    <!-- Recent Leads -->
    <div class="mt-8 bg-white rounded-lg shadow">
      <div class="p-4 border-b">
        <h2 class="text-lg font-semibold">Recent Leads</h2>
      </div>
      <div v-if="store.leads.length" class="overflow-x-auto">
        <table class="w-full min-w-full">
          <thead class="bg-gray-50">
            <tr>
              <th class="px-4 py-3 text-left text-xs font-medium text-gray-500">Company</th>
              <th class="px-4 py-3 text-left text-xs font-medium text-gray-500">Contact</th>
              <th class="px-4 py-3 text-left text-xs font-medium text-gray-500">Score</th>
              <th class="px-4 py-3 text-left text-xs font-medium text-gray-500">Status</th>
              <th class="px-4 py-3 text-left text-xs font-medium text-gray-500">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            <tr v-for="lead in store.leads" :key="lead.id" class="hover:bg-gray-50">
              <td class="px-4 py-3 font-medium">{{ lead.company_name }}</td>
              <td class="px-4 py-3 text-gray-600">{{ lead.contact_name }}</td>
              <td class="px-4 py-3">
                <span
                  v-if="lead.lead_score"
                  :class="{
                    'bg-green-100 text-green-800': lead.lead_score === 'A',
                    'bg-yellow-100 text-yellow-800': lead.lead_score === 'B',
                    'bg-red-100 text-red-800': lead.lead_score === 'C',
                  }"
                  class="px-2 py-1 rounded text-xs font-medium"
                >
                  {{ lead.lead_score }}
                </span>
                <span v-else class="text-gray-400">-</span>
              </td>
              <td class="px-4 py-3">
                <span class="px-2 py-1 rounded text-xs font-medium bg-gray-100">
                  {{ lead.status }}
                </span>
              </td>
              <td class="px-4 py-3">
                <button
                  v-if="lead.status === 'new'"
                  @click="startWorkflow(lead.id)"
                  :disabled="store.isWorkflowRunning"
                  class="px-3 py-1 bg-blue-600 text-white text-xs rounded hover:bg-blue-700 disabled:opacity-50"
                >
                  Run Agents
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <p v-else class="p-8 text-center text-gray-400">
        No leads yet.
        <router-link :to="`/company/${$route.params.companyId}/leads/new`" class="text-blue-600 hover:underline">Create one</router-link>
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { useDashboardStore } from '../stores/dashboard'
import { workflowApi } from '../api/client'
import AgentPipeline from '../components/AgentPipeline.vue'
import PendingOffers from '../components/PendingOffers.vue'

const store = useDashboardStore()
const pendingOffersRef = ref<InstanceType<typeof PendingOffers> | null>(null)

const pipelineStages = [
  { key: 'lead_contacted', name: 'Lead Contacted', bg: 'bg-blue-50', text: 'text-blue-700', label: 'text-blue-500' },
  { key: 'in_pipeline',   name: 'In Pipeline',    bg: 'bg-indigo-50', text: 'text-indigo-700', label: 'text-indigo-500' },
  { key: 'offer_sent',    name: 'Offer Sent',     bg: 'bg-purple-50', text: 'text-purple-700', label: 'text-purple-500' },
]

function formatCurrency(value: number) {
  if (!value) return '€0'
  return '€' + value.toLocaleString('el-GR', { minimumFractionDigits: 0, maximumFractionDigits: 0 })
}

const agentLabels: Record<string, string> = {
  marketing: '🎯 Marketing',
  sales: '💼 Sales',
  legal: '⚖️ Legal',
  accounting: '📊 Accounting',
  email: '📧 Email',
}

function getAgentLabel(agent: string) {
  return agentLabels[agent] || agent
}

function getEventClass(event: any) {
  const base: Record<string, string> = {
    marketing: 'border-marketing bg-marketing-light',
    sales: 'border-sales bg-sales-light',
    legal: 'border-legal bg-legal-light',
    accounting: 'border-accounting bg-accounting-light',
    email: 'border-email bg-email-light',
  }
  return base[event.agent] || 'border-gray-200'
}

function formatTime(ts: string) {
  return new Date(ts).toLocaleTimeString()
}

async function startWorkflow(leadId: string) {
  store.setWorkflowRunning(leadId)
  try {
    await workflowApi.start(leadId)
  } catch (e: any) {
    console.error('Workflow error:', e)
    store.isWorkflowRunning = false
  }
}

// Reload pending offers panel whenever a new offer draft SSE event arrives
watch(() => store.agentEvents[0], (event) => {
  if (event?.type === 'offer_pending_approval') {
    pendingOffersRef.value?.load()
  }
})

onMounted(() => {
  store.refreshAll()
  store.connectSSE()
})

onUnmounted(() => {
  store.disconnectSSE()
})
</script>
